services:
  # Azurite (Storage Emulator)
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    container_name: sutra-azurite
    command: "azurite --blobHost 0.0.0.0 --queueHost 0.0.0.0 --tableHost 0.0.0.0"
    ports:
      - "10000:10000" # Blob service
      - "10001:10001" # Queue service
      - "10002:10002" # Table service
    volumes:
      - azurite-data:/data
    networks:
      - sutra-network

  # Frontend (Web App)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sutra-frontend
    environment:
      - NODE_ENV=development
      - VITE_API_BASE_URL=http://localhost:7071
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      functions-api:
        condition: service_healthy
    networks:
      - sutra-network

  # Azure Functions (API) - No Cosmos dependency for ARM64 compatibility
  functions-api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    container_name: sutra-functions-api
    environment:
      - AzureWebJobsStorage=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1;QueueEndpoint=http://azurite:10001/devstoreaccount1;TableEndpoint=http://azurite:10002/devstoreaccount1;
      - FUNCTIONS_WORKER_RUNTIME=python
      - FUNCTIONS_EXTENSION_VERSION=~4
      - ENVIRONMENT=development
      # Use a mock/disabled Cosmos configuration
      - COSMOS_DB_ENDPOINT=https://localhost:8081
      - COSMOS_DB_KEY=C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==
      - COSMOS_DB_DATABASE=sutra-e2e
      - COSMOS_DB_DISABLED=true # Custom flag to disable Cosmos operations
      - KEY_VAULT_URL=mock://localhost/e2e-vault
      - STORAGE_ACCOUNT_URL=http://azurite:10000/devstoreaccount1
      - AZURE_CLIENT_ID=e2e-client-id
      - AZURE_CLIENT_SECRET=e2e-client-secret
      - AZURE_TENANT_ID=e2e-tenant-id
      - LOG_LEVEL=INFO
      - AzureWebJobsScriptRoot=/home/site/wwwroot
      - AzureFunctionsJobHost__Logging__Console__IsEnabled=true
    ports:
      - "7071:7071"
    volumes:
      - ./api:/home/site/wwwroot
    depends_on:
      azurite:
        condition: service_started
    networks:
      - sutra-network
    healthcheck:
      test:
        [
          "CMD",
          "sh",
          "-c",
          "curl -f http://localhost:7071/api/health --max-time 5 || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 180s

volumes:
  azurite-data:

networks:
  sutra-network:
    driver: bridge
